@baseUrl = https://8080-isabellymira-receitasp2-57znd3e9gg9.ws-us114.gitpod.io

###
GET {{baseUrl}}/quizzes

###
POST {{baseUrl}}/quizzes
Content-Type: application/json

{
    "categoria" : "Categoria do Quiz",
    "id" : 1,
    "nome" : "Exemplo de Quiz",
    "questoes" : [
        {"id" : 1},
        {"id" : 2}
    ]
}

###
PUT {{baseUrl}}/quizzes/1
Content-Type: application/json

{
    "categoria" : "Nova Categoria",
    "id" : 1,
    "nome" : "Exemplo de Quiz Alterado",
    "questoes" : [
        {"id" : 1},
        {"id" : 4}
    ]
}
